[features]
seeds = false
skip-lint = false

[programs.devnet]
thepublic_node_registry = "11111111111111111111111111111112"

[programs.mainnet]
thepublic_node_registry = "11111111111111111111111111111112"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
